name: Documentation

on:
  push:
    branches:
      - main
    tags:
      - 'v*'
  pull_request:

permissions:
  actions: write
  contents: write
  pages: write
  statuses: write

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/install-juliaup@v2
        with:
          channel: '1'
      - uses: julia-actions/cache@v1
      - name: Install dependencies
        shell: julia --project=docs/ --color=yes {0}
        run: |
          using Pkg
          Pkg.develop(path=".")
          Pkg.instantiate()
      - name: Build and deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}
        run: julia --project=docs/ docs/make.jl
